__Linear SVC (Support Vector Classifier) Example__

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [2]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

# Assign colum names to the dataset
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Target']

# Read dataset to pandas dataframe
dataset = pd.read_csv(url, names=names)

In [3]:
dataset.head(5)

sepal-length  sepal-width  petal-length  petal-width       Target
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [4]:
dataset.Target.unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [5]:
X = dataset.loc[:, 'sepal-length':'petal-width' ]
y = dataset.iloc[:, 4]

In [6]:
X.columns

Index(['sepal-length', 'sepal-width', 'petal-length', 'petal-width'], dtype='object')

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [8]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [9]:
from sklearn.svm import LinearSVC

In [10]:
# Create support vector classifier
svc = LinearSVC(C=1.0)

model = svc.fit(X_train, y_train)

In [13]:
test_predictions=svc.predict(X_test)
train_predictions=svc.predict(X_train)

In [14]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test, test_predictions))

print(classification_report(y_test, test_predictions))

print("Train Accuracy:",accuracy_score(y_train, train_predictions)*100)
print("Test Accuracy:",accuracy_score(y_test, test_predictions)*100)

[[ 6  0  0]
 [ 0 10  1]
 [ 0  0 13]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         6
Iris-versicolor       1.00      0.91      0.95        11
 Iris-virginica       0.93      1.00      0.96        13

    avg / total       0.97      0.97      0.97        30

Train Accuracy: 94.16666666666667
Test Accuracy: 96.66666666666667


In [15]:
from sklearn.svm import SVC

__Create a SVC classifier using a linear kernel__

In [22]:
linear_svm = SVC(kernel='linear', C=1,gamma=0.01, random_state=0)
# Train the classifier
linear_svm.fit(X_train, y_train)

test_predictions=linear_svm.predict(X_test)
train_predictions=linear_svm.predict(X_train)

print(confusion_matrix(y_test, test_predictions))

print(classification_report(y_test, test_predictions))

print("Train Accuracy:",accuracy_score(y_train, train_predictions)*100)
print("Test Accuracy:",accuracy_score(y_test, test_predictions)*100)

[[ 6  0  0]
 [ 0 11  0]
 [ 0  0 13]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         6
Iris-versicolor       1.00      1.00      1.00        11
 Iris-virginica       1.00      1.00      1.00        13

    avg / total       1.00      1.00      1.00        30

Train Accuracy: 98.33333333333333
Test Accuracy: 100.0


__Create a SVC classifier using a RBF kernel__

In [23]:
linear_svm = SVC(kernel='rbf', C=1,gamma=0.01, random_state=0)
# Train the classifier
linear_svm.fit(X_train, y_train)

test_predictions=linear_svm.predict(X_test)
train_predictions=linear_svm.predict(X_train)

print(confusion_matrix(y_test, test_predictions))

print(classification_report(y_test, test_predictions))

print("Train Accuracy:",accuracy_score(y_train, train_predictions)*100)
print("Test Accuracy:",accuracy_score(y_test, test_predictions)*100)

[[ 6  0  0]
 [ 0 11  0]
 [ 0  5  8]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         6
Iris-versicolor       0.69      1.00      0.81        11
 Iris-virginica       1.00      0.62      0.76        13

    avg / total       0.89      0.83      0.83        30

Train Accuracy: 90.0
Test Accuracy: 83.33333333333334


__Create a SVC classifier using a Polynomial kernel__

In [25]:
linear_svm = SVC(kernel='poly', C=1,gamma=0.01, random_state=0)
# Train the classifier
linear_svm.fit(X_train, y_train)

test_predictions=linear_svm.predict(X_test)
train_predictions=linear_svm.predict(X_train)

print(confusion_matrix(y_test, test_predictions))

print(classification_report(y_test, test_predictions))

print("Train Accuracy:",accuracy_score(y_train, train_predictions)*100)
print("Test Accuracy:",accuracy_score(y_test, test_predictions)*100)

[[ 6  0  0]
 [11  0  0]
 [13  0  0]]
                 precision    recall  f1-score   support

    Iris-setosa       0.20      1.00      0.33         6
Iris-versicolor       0.00      0.00      0.00        11
 Iris-virginica       0.00      0.00      0.00        13

    avg / total       0.04      0.20      0.07        30

Train Accuracy: 36.666666666666664
Test Accuracy: 20.0


C:\Anaconda\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
